// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: casbin_rule.sql

package db

import (
	"context"
)

const selectAllCasbinRule = `-- name: SelectAllCasbinRule :many
SELECT
    id, p_type, v0, v1, v2, v3, v4, v5
FROM
    notes.casbin_rule
`

func (q *Queries) SelectAllCasbinRule(ctx context.Context) ([]NotesCasbinRule, error) {
	rows, err := q.db.Query(ctx, selectAllCasbinRule)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotesCasbinRule
	for rows.Next() {
		var i NotesCasbinRule
		if err := rows.Scan(
			&i.ID,
			&i.PType,
			&i.V0,
			&i.V1,
			&i.V2,
			&i.V3,
			&i.V4,
			&i.V5,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
